from django.contrib import admin
from django.apps import apps

from trading_insights.models import (
    Position
)


custom_model_admins = [
    "position"
]

for model in apps.get_models():
    if (
        model._meta.app_label == "trading_insights"
        and model._meta.model_name.lower() not in custom_model_admins
    ):
        @admin.register(model)
        class AutoGeneratedModelAdmin(admin.ModelAdmin):
            pass

# -------------------------------
# Start customizing admin models
# -------------------------------

@admin.register(Position)
class PositionModelAdmin(admin.ModelAdmin):
    pass
