# Generated by Django 4.2 on 2024-09-29 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Account Name")),
                (
                    "broker",
                    models.CharField(
                        blank=True, default="", max_length=256, verbose_name="Broker"
                    ),
                ),
                (
                    "account_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Account ID",
                    ),
                ),
                (
                    "starting_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=13,
                        verbose_name="Starting Balance",
                    ),
                ),
            ],
            options={"verbose_name": "Account", "verbose_name_plural": "Accounts"},
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trading_insights.account",
                    ),
                ),
            ],
            options={"verbose_name": "Scenario", "verbose_name_plural": "Scenarios"},
        ),
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Symbol")),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Extended name",
                    ),
                ),
                (
                    "symbol_type",
                    models.CharField(
                        choices=[
                            ("forex", "Forex"),
                            ("commodity", "Commodity"),
                            ("stock", "Stock"),
                        ],
                        default="forex",
                        max_length=32,
                        verbose_name="Type",
                    ),
                ),
                (
                    "pip_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=0.0001,
                        max_digits=6,
                        verbose_name="Pip value",
                    ),
                ),
            ],
            options={"verbose_name": "Symbol", "verbose_name_plural": "Symbols"},
        ),
        migrations.CreateModel(
            name="ScenarioLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "start_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Start Amount"
                    ),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Target Amount"
                    ),
                ),
                (
                    "daily_profit_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Daily Target Profit",
                    ),
                ),
                (
                    "weekly_withdrawal_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=13,
                        verbose_name="Weekly Withdrawal Amount",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="trading_insights.scenario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scenario Line",
                "verbose_name_plural": "Scenario Lines",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Position ID",
                    ),
                ),
                (
                    "position_type",
                    models.CharField(
                        choices=[
                            ("buy", "Buy"),
                            ("sell", "Sell"),
                            ("deposit", "Deposit"),
                            ("withdraw", "Withdraw"),
                        ],
                        max_length=16,
                        verbose_name="Type",
                    ),
                ),
                ("open_time", models.DateTimeField(verbose_name="Open Time")),
                ("close_time", models.DateTimeField(verbose_name="Open Time")),
                (
                    "volume",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Volume"
                    ),
                ),
                (
                    "open_price",
                    models.DecimalField(
                        decimal_places=5, max_digits=10, verbose_name="Open Price"
                    ),
                ),
                (
                    "stop_loss",
                    models.DecimalField(
                        decimal_places=5, max_digits=10, verbose_name="Stop Loss"
                    ),
                ),
                (
                    "take_profit",
                    models.DecimalField(
                        decimal_places=5, max_digits=10, verbose_name="Take Profit"
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        decimal_places=5, max_digits=10, verbose_name="Close Price"
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Commission"
                    ),
                ),
                (
                    "swap",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Swap"
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2, max_digits=13, verbose_name="Profit"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Deposited or withdrawn amount.",
                        max_digits=13,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trading_insights.account",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trading_insights.symbol",
                    ),
                ),
            ],
            options={"verbose_name": "Position", "verbose_name_plural": "Positions"},
        ),
    ]
