# Generated by Django 4.2 on 2024-09-29 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trading_insights", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Created at",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted at"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="last_updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Last update"
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Created at",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted at"
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="last_updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Last update"
            ),
        ),
        migrations.AddField(
            model_name="scenario",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Created at",
            ),
        ),
        migrations.AddField(
            model_name="scenario",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scenario",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted at"
            ),
        ),
        migrations.AddField(
            model_name="scenario",
            name="last_updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Last update"
            ),
        ),
        migrations.AddField(
            model_name="scenarioline",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Created at",
            ),
        ),
        migrations.AddField(
            model_name="scenarioline",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scenarioline",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted at"
            ),
        ),
        migrations.AddField(
            model_name="scenarioline",
            name="last_updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Last update"
            ),
        ),
        migrations.AddField(
            model_name="symbol",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Created at",
            ),
        ),
        migrations.AddField(
            model_name="symbol",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="symbol",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted at"
            ),
        ),
        migrations.AddField(
            model_name="symbol",
            name="last_updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Last update"
            ),
        ),
    ]
